# Generated by Django 5.1.2 on 2024-10-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal User'), ('admin', 'Admin User')], default='normal', max_length=10),
        ),
    ]
